import '@/styles/globals.css'
import React from 'react'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
   
  return (
     <>
      <Head>
        <title>Erasto portfolio</title>
        <meta name = "description" content = "Generated by create next app" />
        <link rel = "icon" href = "/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}
